# Generated by Django 3.2.5 on 2021-08-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
